title: Anna Wallin's Projects
description: > # this means to ignore newlines until "baseurl:"
  Marketing analytics projects. Data visualization projects. Portfolio.

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "dark"
# Site Author
author:
  name: "Anna Wallin"
  avatar: ![image](https://user-images.githubusercontent.com/76073032/102818657-b8886000-4397-11eb-9e1e-d56821636766.png)
  bio: "A grad student in Austin"
  location: "Texas"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/annawallin"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/anna-r-wallin/"
  
