title: Anna Wallin's Projects
author: Anna Wallin
theme: jekyll-theme-slate
description: > # this means to ignore newlines until "baseurl:"
  Marketing analytics projects. Data visualization projects. Portfolio.

  
