title: Anna Wallin's Projects
author: Anna Wallin
theme: minima
email: anna.r.wallin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marketing analytics projects. Data visualization projects. Portfolio.

# social links
github_username:  annawallin
linkedin_username: [https://www.linkedin.com/in/anna-r-wallin/](Anna Rosemarie Wallin)
show_excerpts: true # set to false to remove excerpts on the homepage
