title: Anna Wallin's Projects
author: Anna Wallin
theme: jekyll-theme-slate
description: > # this means to ignore newlines until "baseurl:"
  Marketing analytics projects. Data visualization projects. Portfolio.

# social links
github_username:  annawallin
linkedin_username: Anna Rosemarie Wallin
show_excerpts: true # set to false to remove excerpts on the homepage

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<a href="#" class="fa fa-facebook"></a>

/* Style all font awesome icons */
.fa {
  padding: 20px;
  font-size: 30px;
  width: 50px;
  text-align: center;
  text-decoration: none;
}

/* Add a hover effect if you want */
.fa:hover {
  opacity: 0.7;
}

/* Set a specific color for each brand */

/* Facebook */
.fa-facebook {
  background: #3B5998;
  color: white;
}
