title: Anna Wallin's Projects
author: Anna Wallin
remote_theme: pmarsceill/just-the-docs
description: > # this means to ignore newlines until "baseurl:"
  Marketing analytics projects. Data visualization projects. Portfolio.
location: Texas


  
